---
openapi: 3.0.3
info:
  title: twitter-rails-api
  version: 1.0.0
servers: []
paths:
  "/api/auth/sign_up":
    post:
      summary: sign_up
      tags:
      - API::Authentication
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                authentication:
                  type: object
                  properties:
                    username:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
            example:
              authentication:
                username: steve.harrington
                email: steve.harrington@hawkins.com
                password: best_babysitter_ever
      responses:
        '200':
          description: returns the details of the newly-registered user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  name:
                    nullable: true
              example:
                id: 1
                username: steve.harrington
                email: steve.harrington@hawkins.com
                created_at: '2022-06-20T14:14:10.122Z'
                updated_at: '2022-06-20T14:14:10.122Z'
                name:
        '400':
          description: returns error message in required fields are are not specified
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      password:
                        type: array
                        items:
                          type: string
              example:
                errors:
                  password:
                  - can't be blank
  "/api/auth/login":
    post:
      summary: login
      tags:
      - API::Authentication
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                authentication:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
            example:
              authentication:
                email: steve.harrington@hawkins.com
                password: password
      responses:
        '200':
          description: returns a confirmation message on success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Logged in successfully.
        '401':
          description: returns an error message on failed login
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: Login failed. Unauthorized.
  "/api/auth/logout":
    post:
      summary: logout
      tags:
      - API::Authentication
      responses:
        '200':
          description: returns a confirmation message on success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Logged out successfully.
        '401':
          description: returns an error message if unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
  "/api/tweets":
    get:
      summary: list
      tags:
      - API::Tweet
      responses:
        '200':
          description: returns a list of Tweets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    content:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    user:
                      type: object
                      properties:
                        id:
                          type: integer
                        username:
                          type: string
                        email:
                          type: string
                        name:
                          nullable: true
              example:
              - id: 1
                content: My first tweet. Welcome to Twitter.
                created_at: '2022-06-20T14:14:10.183Z'
                updated_at: '2022-06-20T14:14:10.183Z'
                user:
                  id: 5
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name:
              - id: 2
                content: Anothah one.
                created_at: '2022-06-20T14:14:10.184Z'
                updated_at: '2022-06-20T14:14:10.184Z'
                user:
                  id: 5
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name:
              - id: 3
                content: Third time's a charm.
                created_at: '2022-06-20T14:14:10.186Z'
                updated_at: '2022-06-20T14:14:10.186Z'
                user:
                  id: 5
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name:
        '401':
          description: returns an error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
  "/api/users":
    get:
      summary: list
      tags:
      - API::User
      responses:
        '200':
          description: returns a list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    email:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    name:
                      nullable: true
                    tweets:
                      type: array
                      items:
                        nullable: true
              example:
              - id: 6
                username: dustin.henderson
                email: dustin.henderson@hawkins.com
                created_at: '2022-06-20T14:14:10.201Z'
                updated_at: '2022-06-20T14:14:10.201Z'
                name:
                tweets: []
        '401':
          description: returns an error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
