---
openapi: 3.0.3
info:
  title: twitter-rails-api
  version: 1.0.0
servers: []
paths:
  "/api/auth/sign_up":
    post:
      summary: sign_up
      tags:
      - API::Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authentication:
                  type: object
                  properties:
                    username:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
            example:
              authentication:
                username: steve.harrington
                email: steve.harrington@hawkins.com
                password: best_babysitter_ever
      responses:
        '200':
          description: returns the details of the newly-registered user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  name:
                    nullable: true
              example:
                id: 2
                username: steve.harrington
                email: steve.harrington@hawkins.com
                created_at: '2022-06-22T03:02:02.547Z'
                updated_at: '2022-06-22T03:02:02.547Z'
                name:
        '400':
          description: returns error message in required fields are are not specified
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      password:
                        type: array
                        items:
                          type: string
              example:
                errors:
                  password:
                  - can't be blank
  "/api/auth/login":
    post:
      summary: login
      tags:
      - API::Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authentication:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
            example:
              authentication:
                email: steve.harrington@hawkins.com
                password: password
      responses:
        '200':
          description: returns a confirmation message on success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Logged in successfully.
        '401':
          description: returns an error message on failed login
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: Login failed. Unauthorized.
  "/api/auth/logout":
    post:
      summary: logout
      tags:
      - API::Authentication
      responses:
        '200':
          description: returns a confirmation message on success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Logged out successfully.
        '401':
          description: returns an error message if unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
  "/api/tweets":
    get:
      summary: index
      tags:
      - API::Tweet
      responses:
        '200':
          description: returns a list of Tweets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    content:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    url:
                      type: string
                    user:
                      type: object
                      properties:
                        id:
                          type: integer
                        username:
                          type: string
                        email:
                          type: string
                        name:
                          type: string
              example:
              - id: 1
                content: My first tweet. Welcome to Twitter.
                created_at: '2022-06-22T03:02:02.633Z'
                updated_at: '2022-06-22T03:02:02.633Z'
                url: "/api/tweets/1"
                user:
                  id: 10
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name: Dustin Henderson
              - id: 2
                content: Anothah one.
                created_at: '2022-06-22T03:02:02.636Z'
                updated_at: '2022-06-22T03:02:02.636Z'
                url: "/api/tweets/2"
                user:
                  id: 10
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name: Dustin Henderson
              - id: 3
                content: Third time's a charm.
                created_at: '2022-06-22T03:02:02.637Z'
                updated_at: '2022-06-22T03:02:02.637Z'
                url: "/api/tweets/3"
                user:
                  id: 10
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name: Dustin Henderson
        '401':
          description: returns an error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
    post:
      summary: create
      tags:
      - API::Tweet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tweet:
                  type: object
                  properties:
                    content:
                      type: string
            example:
              tweet:
                content: Yet another Tweet...
      responses:
        '200':
          description: creates a Tweet
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  user_id:
                    type: integer
              example:
                id: 4
                content: Yet another Tweet...
                created_at: '2022-06-22T03:02:02.662Z'
                updated_at: '2022-06-22T03:02:02.662Z'
                user_id: 12
        '401':
          description: returns an error message if unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
  "/api/tweets/{id}":
    get:
      summary: show
      tags:
      - API::Tweet
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 5
      responses:
        '200':
          description: returns the details of a Tweet
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      email:
                        type: string
                      name:
                        type: string
              example:
                id: 5
                content: Another one bites the dust!
                created_at: '2022-06-22T03:02:02.680Z'
                updated_at: '2022-06-22T03:02:02.680Z'
                user:
                  id: 14
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name: Dustin Henderson
        '401':
          description: returns an error on invalid Tweet ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
  "/api/users":
    get:
      summary: index
      tags:
      - API::User
      responses:
        '200':
          description: returns a list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    email:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    name:
                      type: string
                    tweets:
                      type: array
                      items:
                        nullable: true
              example:
              - id: 16
                username: dustin.henderson
                email: dustin.henderson@hawkins.com
                created_at: '2022-06-22T03:02:02.700Z'
                updated_at: '2022-06-22T03:02:02.700Z'
                name: Dustin Henderson
                tweets: []
        '401':
          description: returns an error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
