---
openapi: 3.0.3
info:
  title: twitter-rails-api
  version: 1.0.0
servers: []
paths:
  "/api/users":
    get:
      summary: list
      tags:
      - API::User
      responses:
        '200':
          description: returns a list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  nullable: true
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    email:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    name:
                      nullable: true
                    tweets:
                      type: array
                      items:
                        nullable: true
              example:
              - id: 2
                username: dustin.henderson
                email: dustin.henderson@hawkins.com
                created_at: '2022-06-17T10:44:30.677Z'
                updated_at: '2022-06-17T10:44:30.677Z'
                name:
                tweets: []
