---
openapi: 3.0.3
info:
  title: twitter-rails-api
  version: 1.0.0
servers: []
paths:
  "/api/auth/sign_up":
    post:
      summary: sign_up
      tags:
      - API::Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authentication:
                  type: object
                  properties:
                    username:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
            example:
              authentication:
                username: steve.harrington
                email: steve.harrington@hawkins.com
                password: best_babysitter_ever
      responses:
        '200':
          description: returns the details of the newly-registered user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  name:
                    nullable: true
              example:
                id: 339
                username: steve.harrington
                email: steve.harrington@hawkins.com
                created_at: '2022-06-22T05:57:56.834Z'
                updated_at: '2022-06-22T05:57:56.834Z'
                name:
        '400':
          description: returns error message in required fields are are not specified
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      password:
                        type: array
                        items:
                          type: string
              example:
                errors:
                  password:
                  - can't be blank
  "/api/auth/login":
    post:
      summary: login
      tags:
      - API::Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authentication:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
            example:
              authentication:
                email: steve.harrington@hawkins.com
                password: password
      responses:
        '200':
          description: returns a confirmation message on success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Logged in successfully.
        '401':
          description: returns an error message on failed login
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: Login failed. Unauthorized.
  "/api/auth/logout":
    post:
      summary: logout
      tags:
      - API::Authentication
      responses:
        '200':
          description: returns a confirmation message on success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Logged out successfully.
        '401':
          description: returns an error message if unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
  "/api/tweets":
    get:
      summary: index
      tags:
      - API::Tweet
      responses:
        '200':
          description: returns a list of Tweets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    content:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    url:
                      type: string
                    user:
                      type: object
                      properties:
                        id:
                          type: integer
                        username:
                          type: string
                        email:
                          type: string
                        name:
                          type: string
              example:
              - id: 136
                content: My first tweet. Welcome to Twitter.
                created_at: '2022-06-22T05:57:56.916Z'
                updated_at: '2022-06-22T05:57:56.916Z'
                url: "/api/tweets/136"
                user:
                  id: 347
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name: Dustin Henderson
              - id: 137
                content: Anothah one.
                created_at: '2022-06-22T05:57:56.918Z'
                updated_at: '2022-06-22T05:57:56.918Z'
                url: "/api/tweets/137"
                user:
                  id: 347
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name: Dustin Henderson
              - id: 138
                content: Third time's a charm.
                created_at: '2022-06-22T05:57:56.919Z'
                updated_at: '2022-06-22T05:57:56.919Z'
                url: "/api/tweets/138"
                user:
                  id: 347
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name: Dustin Henderson
        '401':
          description: returns an error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
    post:
      summary: create
      tags:
      - API::Tweet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tweet:
                  type: object
                  properties:
                    content:
                      type: string
            example:
              tweet:
                content: Yet another Tweet.
      responses:
        '200':
          description: creates a Tweet
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  user_id:
                    type: integer
              example:
                id: 139
                content: Yet another Tweet.
                created_at: '2022-06-22T05:57:56.947Z'
                updated_at: '2022-06-22T05:57:56.947Z'
                user_id: 349
        '401':
          description: returns an error message if unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
  "/api/tweets/{id}":
    get:
      summary: show
      tags:
      - API::Tweet
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 140
      responses:
        '200':
          description: returns the details of a Tweet
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      email:
                        type: string
                      name:
                        type: string
              example:
                id: 140
                content: Another one bites the dust!
                created_at: '2022-06-22T05:57:56.965Z'
                updated_at: '2022-06-22T05:57:56.965Z'
                user:
                  id: 351
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name: Dustin Henderson
        '401':
          description: returns an error if unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
        '400':
          description: returns an error if Tweet with a given ID does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: Couldn't find Tweet with 'id'=2
    delete:
      summary: destroy
      tags:
      - API::Tweet
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 143
      responses:
        '200':
          description: returns the details of the deleted Tweet
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      email:
                        type: string
                      name:
                        type: string
              example:
                id: 143
                content: Might delete this later.
                created_at: '2022-06-22T05:57:56.999Z'
                updated_at: '2022-06-22T05:57:56.999Z'
                user:
                  id: 354
                  username: dustin.henderson
                  email: dustin.henderson@hawkins.com
                  name: Dustin Henderson
        '400':
          description: returns an error if Tweet with a given ID does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: Couldn't find Tweet with 'id'=88
  "/api/users":
    get:
      summary: index
      tags:
      - API::User
      responses:
        '200':
          description: returns a list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    email:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    name:
                      type: string
                    tweets:
                      type: array
                      items:
                        nullable: true
              example:
              - id: 356
                username: dustin.henderson
                email: dustin.henderson@hawkins.com
                created_at: '2022-06-22T05:57:57.019Z'
                updated_at: '2022-06-22T05:57:57.019Z'
                name: Dustin Henderson
                tweets: []
        '401':
          description: returns an error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON Web Token not found.
